import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  scroll: { paddingHorizontal: 20, paddingTop: 56, paddingBottom: 120 },
  headerArea: { marginBottom: 28 },
  pageTitle: { fontSize: 28, fontWeight: '800', marginBottom: 4 },
  pageSubtitle: { fontSize: 14, fontWeight: '500' },
  sectionLabel: { fontSize: 10, fontWeight: '800', letterSpacing: 1.5, marginBottom: 14 },
  scoreCard: { borderRadius: 24, padding: 28, alignItems: 'center', marginBottom: 24, overflow: 'hidden', borderWidth: 1 },
  scoreGlow: { position: 'absolute', top: -50, left: '30%', width: 200, height: 200, borderRadius: 100 },
  scoreCircle: { width: 130, height: 130, borderRadius: 65, justifyContent: 'center', alignItems: 'center', marginBottom: 16, borderWidth: 5 },
  scoreValue: { fontSize: 48, fontWeight: '900' },
  scoreLabel: { fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.5, marginBottom: 12 },
  trendBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 999 },
  trendText: { fontSize: 12, fontWeight: '700' },
  metricsCard: { borderRadius: 22, padding: 20, marginBottom: 24, borderWidth: 1 },
  metricsTitle: { fontSize: 16, fontWeight: '800', marginBottom: 4 },
  metricsSub: { fontSize: 12, marginBottom: 20, fontWeight: '500' },
  progressGroup: { gap: 18 },
  progressItem: { gap: 8 },
  progressLabelRow: { flexDirection: 'row', justifyContent: 'space-between' },
  progressLabel: { fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5 },
  progressPct: { fontSize: 12, fontWeight: '700' },
  progressTrack: { width: '100%', height: 8, borderRadius: 999, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 999 },
  summaryRow: { flexDirection: 'row', gap: 10, marginBottom: 24 },
  summaryCard: { flex: 1, borderRadius: 18, padding: 16, alignItems: 'center', borderWidth: 1 },
  summaryIcon: { width: 40, height: 40, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  summaryValue: { fontSize: 22, fontWeight: '800' },
  summaryLabel: { fontSize: 9, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5, marginTop: 4 },
  trendCard: { borderRadius: 22, padding: 20, marginBottom: 24, borderWidth: 1 },
  trendTitle: { fontSize: 16, fontWeight: '800', marginBottom: 20 },
  trendBarGroup: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', height: 140 },
  barCol: { flex: 1, alignItems: 'center' },
  barValue: { fontSize: 9, fontWeight: '700', marginBottom: 6 },
  barTrack: { width: 20, height: 100, borderRadius: 10, justifyContent: 'flex-end', overflow: 'hidden' },
  barFill: { width: '100%', borderRadius: 10 },
  barLabel: { fontSize: 10, fontWeight: '700', marginTop: 8 },
});
