import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  scroll: { paddingHorizontal: 20, paddingTop: 56, paddingBottom: 120 },
  headerArea: { marginBottom: 28 },
  pageTitle: { fontSize: 28, fontWeight: '800', marginBottom: 4 },
  pageSubtitle: { fontSize: 14, fontWeight: '500' },
  sectionLabel: { fontSize: 10, fontWeight: '800', letterSpacing: 1.5, marginBottom: 14 },
  heroCard: { borderRadius: 24, padding: 28, alignItems: 'center', marginBottom: 28, overflow: 'hidden', borderWidth: 1 },
  heroGlow: { position: 'absolute', top: -60, right: -60, width: 180, height: 180, borderRadius: 90 },
  heroGlow2: { position: 'absolute', bottom: -40, left: -40, width: 120, height: 120, borderRadius: 60 },
  iconRing: { width: 100, height: 100, borderRadius: 50, justifyContent: 'center', alignItems: 'center', marginBottom: 20, borderWidth: 2 },
  iconInner: { width: 72, height: 72, borderRadius: 36, justifyContent: 'center', alignItems: 'center' },
  heroTitle: { fontSize: 20, fontWeight: '800', marginBottom: 10 },
  heroDesc: { fontSize: 13, textAlign: 'center', lineHeight: 22, marginBottom: 24, fontWeight: '500' },
  scanBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10,
    borderRadius: 16, height: 52, width: '100%',
    elevation: 8, shadowColor: '#3b82f6', shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3, shadowRadius: 12,
  },
  scanBtnText: { fontSize: 15, fontWeight: '700', color: '#fff' },
  capRow: { flexDirection: 'row', gap: 12, marginBottom: 28 },
  capCard: { flex: 1, borderRadius: 18, padding: 18, borderWidth: 1 },
  capIcon: { width: 44, height: 44, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
  capTitle: { fontSize: 13, fontWeight: '700', marginBottom: 4 },
  capSub: { fontSize: 11, fontWeight: '500' },
  defectGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 28 },
  defectChip: { flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, borderWidth: 1 },
  defectText: { fontSize: 11, fontWeight: '600' },
  emptyState: { borderRadius: 18, padding: 32, alignItems: 'center', borderWidth: 1 },
  emptyIcon: { width: 56, height: 56, borderRadius: 16, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
  emptyText: { fontSize: 14, fontWeight: '700', marginBottom: 4 },
  emptySubtext: { fontSize: 12, fontWeight: '500' },
});
