import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f7fa' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 56,
    paddingHorizontal: 20,
    paddingBottom: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e1e3e8',
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: { fontSize: 17, fontWeight: '800', color: '#191c1d' },
  headerRight: { width: 36 },

  statsBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 14,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e1e3e8',
  },
  statItem: { alignItems: 'center' },
  statNumber: { fontSize: 20, fontWeight: '800', color: '#005bbf' },
  statLabel: { fontSize: 10, fontWeight: '600', color: '#727785', letterSpacing: 0.8, marginTop: 2 },

  scroll: { padding: 20, paddingBottom: 100 },

  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  sectionTitle: { fontSize: 13, fontWeight: '700', color: '#525f73', letterSpacing: 1 },
  sectionBadge: {
    backgroundColor: '#e8f0fe',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  sectionBadgeText: { fontSize: 11, fontWeight: '700', color: '#005bbf' },
  label: {
    fontSize: 12,
    fontWeight: '700',
    color: '#525f73',
    marginBottom: 8,
    letterSpacing: 0.5,
    marginTop: 4,
  },

  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e1e3e8',
    marginBottom: 12,
    overflow: 'hidden',
  },
  cardContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 16,
  },
  cardIndex: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#e8f0fe',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    marginTop: 2,
  },
  cardIndexText: { fontSize: 12, fontWeight: '800', color: '#005bbf' },
  cardBody: { flex: 1 },
  questionInput: {
    fontSize: 15,
    fontWeight: '500',
    color: '#191c1d',
    padding: 0,
    minHeight: 22,
  },
  questionInputReadonly: {
    fontSize: 15,
    fontWeight: '500',
    color: '#191c1d',
  },
  deleteBtn: {
    padding: 6,
    marginLeft: 8,
  },

  answerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 14,
    paddingTop: 4,
    gap: 8,
  },
  answerChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#d1d5db',
    backgroundColor: 'transparent',
    gap: 4,
  },
  answerChipActive: {
    borderColor: '#005bbf',
    backgroundColor: '#e8f0fe',
  },
  answerChipText: { fontSize: 12, fontWeight: '600', color: '#727785' },
  answerChipTextActive: { color: '#005bbf' },

  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e1e3e8',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 8,
  },
  footerRow: {
    flexDirection: 'row',
    gap: 12,
  },
  addBtn: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 14,
    height: 52,
    borderWidth: 1.5,
    borderColor: '#005bbf',
    backgroundColor: '#eef4ff',
    gap: 6,
  },
  addBtnText: { fontSize: 14, fontWeight: '700', color: '#005bbf' },
  saveBtn: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 14,
    height: 52,
    backgroundColor: '#005bbf',
    gap: 6,
    shadowColor: '#005bbf',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  saveBtnText: { fontSize: 14, fontWeight: '800', color: '#fff' },

  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
  },
  emptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: '#e8f0fe',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  emptyTitle: { fontSize: 16, fontWeight: '700', color: '#191c1d', marginBottom: 6 },
  emptySubtitle: { fontSize: 13, color: '#727785', textAlign: 'center', lineHeight: 20 },
});
